### PR TITLE
Add build status badge and enable coverage reports (via coveralls)

### PR DESCRIPTION
**Pull request by israelroldan**
With the increasing interest in this great project, I figured it was a good time to add the build status badge as well as the coverage reports.

I hope you agree!

Note: before merging this PR you may want to [enable coveralls for this repo](https://coveralls.io/repos/new) (free for open source projects). The badge is already in the README and it is ready to roll.

### CODE REVIEW

**Comment by piranna** [comment]
For some reason, the badges are not correctly shown on the readme page...

**Comment by piranna** [comment]
Ok, seems that's due to the mixture of HTML and markdown on the same page, HTML should be replaced for their equivalents.

**Comment by gliechtenstein** [comment]
@israelroldan thanks for the PR! I approved coveralls and merged the PR but the stats are not showing up for some reason. Maybe I need to make an additional push for it to kick in?

@piranna I think this was because of a line break. Github became very strict about these things recently for some reason, and it even breaks READMEs from existing repos that used to work fine (Some of my other repos are victims of this). Anyway I just added a line break and now it looks like it's working fine :)

**Comment by piranna** [comment]
Oh, that's cool :-)

**Comment by israelroldan** [comment]
@gliechtenstein thanks for accepting the PR! I think the coverage issue is caused by the eslint output just before the mocha output or one of the deprecation messages in the output.

I'll come back to you with a fix shortly.

**Pull request merged**
